Grading at 12/09/2022:20:23:30.447052
For commit ID 351025571665e4e470b70d490939bd3cf1423951
Grading at Fri Dec  9 03:21:29 PM EST 2022
Doing some basic checking for your submission

Step 1
Checking that cyoa-step1 compiles
rm -f *~ cyoa-step1 cyoa-step2 cyoa-step3 cyoa-step4  cyoa-step1.o  cyoa-step2.o  cyoa-step3.o  cyoa-step4.o
g++ -o cyoa-step1 -ggdb3 -Wall -Werror -pedantic -std=gnu++98 cyoa-step1.cpp util.cpp
The code compiled (good)
Executable cyoa-step1 exists (good)
------------------------------------
Now running YOUR tests for step 1
------------------------------------


1.1: Current test is ./cyoa-step1 /usr/local/ece551/cyoa/story1 < /dev/null
-----------------------------
Your output looks good. Lets check valgrind
  - Valgrind was clean (no errors, no memory leaks)
Valgrind was clean


1.2: Current test is ./cyoa-step1 /usr/local/ece551/cyoa/story2 < /dev/null
-----------------------------
Your output looks good. Lets check valgrind
  - Valgrind was clean (no errors, no memory leaks)
Valgrind was clean


1.3: Current test is ./cyoa-step1 storyTest < /dev/null
-----------------------------
Your output looks good. Lets check valgrind
  - Valgrind was clean (no errors, no memory leaks)
Valgrind was clean


1.4: Current test is ./cyoa-step1 storyTest2 < /dev/null
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
The story contains page declaration line that its page file cannot be opened.
-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


1.5: Current test is ./cyoa-step1 storyTest3 < /dev/null
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
The story contains invalid number.
-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


1.6: Current test is ./cyoa-step1 storyTest4 < /dev/null
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
The story contains invalid number.
-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


1.7: Current test is ./cyoa-step1 storyTest5 < /dev/null
-----------------------------
Your output looks good. Lets check valgrind
  - Valgrind was clean (no errors, no memory leaks)
Valgrind was clean


1.8: Current test is ./cyoa-step1 storyTest6 < /dev/null
-----------------------------
Your output looks good. Lets check valgrind
  - Valgrind was clean (no errors, no memory leaks)
Valgrind was clean


1.9: Current test is ./cyoa-step1 storyTest7 < /dev/null
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
The choice cannot be matched with the current page.
-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


1.10: Current test is ./cyoa-step1 storyTest8 < /dev/null
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
The story contains invalid number.
-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


1.11: Current test is ./cyoa-step1 storyTest9 < /dev/null
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
The current page of the choice shows up before the page declaration.
-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


1.12: Current test is ./cyoa-step1 storyTest10 < /dev/null
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
The win page of the story has choices, but it shouldn't.
-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


1.13: Current test is ./cyoa-step1 storyTest11 < /dev/null
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
The lose page of the story has choices, but it shouldn't.
-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


1.14: Current test is ./cyoa-step1 storyTest12 < /dev/null
-----------------------------
Your output looks good. Lets check valgrind
  - Valgrind was clean (no errors, no memory leaks)
Valgrind was clean


1.15: Current test is ./cyoa-step1 storyTest13 < /dev/null
-----------------------------
Your output looks good. Lets check valgrind
  - Valgrind was clean (no errors, no memory leaks)
Valgrind was clean


1.16: Current test is ./cyoa-step1 storyTest14 < /dev/null
-----------------------------
Your output looks good. Lets check valgrind
  - Valgrind was clean (no errors, no memory leaks)
Valgrind was clean


1.17: Current test is ./cyoa-step1 storyTest15 < /dev/null
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
The pages in this story are not consecutive.
-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


1.18: Current test is ./cyoa-step1 storyTest16 < /dev/null
-----------------------------
Your output looks good. Lets check valgrind
  - Valgrind was clean (no errors, no memory leaks)
Valgrind was clean
No request to check for intermediate deadline completion on step 1

Step 2
Checking that cyoa-step2 compiles
rm -f *~ cyoa-step1 cyoa-step2 cyoa-step3 cyoa-step4  cyoa-step1.o  cyoa-step2.o  cyoa-step3.o  cyoa-step4.o
g++ -o cyoa-step2 -ggdb3 -Wall -Werror -pedantic -std=gnu++98 cyoa-step2.cpp util.cpp
The code compiled (good)
Executable cyoa-step2 exists (good)
------------------------------------
Now running YOUR tests for step 2
------------------------------------


2.1: Current test is ./cyoa-step2 storyTest  <  storyTest/inputs/input0.txt
-----------------------------
Your output looks good. Lets check valgrind
  - Valgrind was clean (no errors, no memory leaks)
Valgrind was clean


2.2: Current test is ./cyoa-step2 storyTest1  <  storyTest1/inputs/input0.txt
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
This story contains undefined page (not N, W nor L).
-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


2.3: Current test is ./cyoa-step2 storyTest2  <  storyTest2/inputs/input0.txt
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
The story contains page declaration line that its page file cannot be opened.
-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


2.4: Current test is ./cyoa-step2 storyTest3  <  storyTest3/inputs/input0.txt
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
The story contains invalid number.
-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


2.5: Current test is ./cyoa-step2 storyTest4  <  storyTest4/inputs/input0.txt
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
The story contains invalid number.
-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


2.6: Current test is ./cyoa-step2 storyTest5  <  storyTest5/inputs/input0.txt
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
The story contains page that the destination page of its choice does not exist.
-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


2.7: Current test is ./cyoa-step2 storyTest6  <  storyTest6/inputs/input0.txt
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
The input cannot finish the story.
-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


2.8: Current test is ./cyoa-step2 storyTest7  <  storyTest7/inputs/input0.txt
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
The choice cannot be matched with the current page.
-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


2.9: Current test is ./cyoa-step2 storyTest8  <  storyTest8/inputs/input0.txt
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
The story contains invalid number.
-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


2.10: Current test is ./cyoa-step2 storyTest9  <  storyTest9/inputs/input0.txt
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
The current page of the choice shows up before the page declaration.
-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


2.11: Current test is ./cyoa-step2 storyTest10  <  storyTest10/inputs/input0.txt
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
The win page of the story has choices, but it shouldn't.
-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


2.12: Current test is ./cyoa-step2 storyTest11  <  storyTest11/inputs/input0.txt
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
The lose page of the story has choices, but it shouldn't.
-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


2.13: Current test is ./cyoa-step2 storyTest12  <  storyTest12/inputs/input0.txt
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
There are pages that are not referenced in this story.
-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


2.14: Current test is ./cyoa-step2 storyTest13  <  storyTest13/inputs/input0.txt
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
There are pages that are not referenced in this story.
-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


2.15: Current test is ./cyoa-step2 storyTest14  <  storyTest14/inputs/input0.txt
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
No win or No lose page in this storty.
-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


2.16: Current test is ./cyoa-step2 storyTest15  <  storyTest15/inputs/input0.txt
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
The pages in this story are not consecutive.
-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


2.17: Current test is ./cyoa-step2 storyTest16  <  storyTest16/inputs/input0.txt
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
The story contains page that the destination page of its choice does not exist.
-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


2.18: Current test is ./cyoa-step2 storyTest  <  storyTest/inputs/input1.txt
-----------------------------
Your output looks good. Lets check valgrind
  - Valgrind was clean (no errors, no memory leaks)
Valgrind was clean


2.19: Current test is ./cyoa-step2 storyTest  <  storyTest/inputs/input2.txt
-----------------------------
Your output looks good. Lets check valgrind
  - Valgrind was clean (no errors, no memory leaks)
Valgrind was clean


2.20: Current test is ./cyoa-step2 storyTest  <  storyTest/inputs/input3.txt
-----------------------------
Your output looks good. Lets check valgrind
  - Valgrind was clean (no errors, no memory leaks)
Valgrind was clean


2.21: Current test is ./cyoa-step2 storyTest  <  storyTest/inputs/input4.txt
-----------------------------
Your output looks good. Lets check valgrind
  - Valgrind was clean (no errors, no memory leaks)
Valgrind was clean


2.22: Current test is ./cyoa-step2 storyTest  <  storyTest/inputs/input5.txt
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
The input cannot finish the story.
-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


2.23: Current test is ./cyoa-step2 storyTest24  <  storyTest24/inputs/input0.txt
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
no char is a valid number.
-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


2.24: Current test is ./cyoa-step2 storyTest25  <  storyTest25/inputs/input0.txt
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
There are pages that are not referenced in this story.
-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


2.25: Current test is ./cyoa-step2 storyTest31  <  storyTest31/inputs/input0.txt
-----------------------------
Your output looks good. Lets check valgrind
  - Valgrind was clean (no errors, no memory leaks)
Valgrind was clean


2.26: Current test is ./cyoa-step2 storyTest32  <  storyTest32/inputs/input0.txt
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
The current page of the choice shows up before the page declaration.
-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


2.27: Current test is ./cyoa-step2 storyTest46  <  storyTest46/inputs/input0.txt
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
The story contains invalid input line.
-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


2.28: Current test is ./cyoa-step2 storyTest45  <  storyTest45/inputs/input0.txt
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
This story contains undefined page (not N, W nor L).
-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


2.29: Current test is ./cyoa-step2 storyTest44  <  storyTest44/inputs/input0.txt
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
The story contains invalid input line.
-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


2.30: Current test is ./cyoa-step2 storyTest43  <  storyTest43/inputs/input0.txt
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
no char is a valid number.
-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


2.31: Current test is ./cyoa-step2 storyTest42  <  storyTest42/inputs/input0.txt
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
The story contains invalid input line.
-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


2.32: Current test is ./cyoa-step2 storyTest41  <  storyTest41/inputs/input0.txt
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
This story contains undefined page (not N, W nor L).
-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


2.33: Current test is ./cyoa-step2 storyTest40  <  storyTest40/inputs/input0.txt
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
There are pages that are not referenced in this story.
-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean
No request to check for intermediate deadline completion on step 2

Step 3
Checking that cyoa-step3 compiles
rm -f *~ cyoa-step1 cyoa-step2 cyoa-step3 cyoa-step4  cyoa-step1.o  cyoa-step2.o  cyoa-step3.o  cyoa-step4.o
g++ -o cyoa-step3 -ggdb3 -Wall -Werror -pedantic -std=gnu++98 cyoa-step3.cpp util.cpp
The code compiled (good)
Executable cyoa-step3 exists (good)
------------------------------------
Now running YOUR tests for step 3
------------------------------------


3.1: Current test is ./cyoa-step3 /usr/local/ece551/cyoa/story1 < /dev/null
-----------------------------
Your output looks good. Lets check valgrind
  - Valgrind was clean (no errors, no memory leaks)
Valgrind was clean


3.2: Current test is ./cyoa-step3 storyTest < /dev/null
-----------------------------
Your output looks good. Lets check valgrind
  - Valgrind was clean (no errors, no memory leaks)
Valgrind was clean


3.3: Current test is ./cyoa-step3 storyTest17 < /dev/null
-----------------------------
Your output looks good. Lets check valgrind
  - Valgrind was clean (no errors, no memory leaks)
Valgrind was clean


3.4: Current test is ./cyoa-step3 storyTest18 < /dev/null
-----------------------------
Your output looks good. Lets check valgrind
  - Valgrind was clean (no errors, no memory leaks)
Valgrind was clean


3.5: Current test is ./cyoa-step3 storyTest30 < /dev/null
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
The win page of the story has choices, but it shouldn't.
-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean
No request to check for intermediate deadline completion on step 3

Step 4
Checking that cyoa-step4 compiles
rm -f *~ cyoa-step1 cyoa-step2 cyoa-step3 cyoa-step4  cyoa-step1.o  cyoa-step2.o  cyoa-step3.o  cyoa-step4.o
g++ -o cyoa-step4 -ggdb3 -Wall -Werror -pedantic -std=gnu++98 cyoa-step4.cpp util.cpp
The code compiled (good)
Executable cyoa-step4 exists (good)
------------------------------------
Now running YOUR tests for step 4
------------------------------------


4.1: Current test is ./cyoa-step4 story3Test26  <  story3Test26/inputs/inputTestInvalidVar.txt
-----------------------------
You considered this a failure case:
The story contains invalid long number. 
But we did not.


4.2: Current test is ./cyoa-step4 story3Test47  <  story3Test47/inputs/input0.txt
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
The story contains invalid input line.
-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


4.3: Current test is ./cyoa-step4 story3Test48  <  story3Test48/inputs/input0.txt
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
The story contains invalid input line.
-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


4.4: Current test is ./cyoa-step4 story3Test49  <  story3Test49/inputs/input0.txt
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
The story contains invalid long number. 
-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


4.5: Current test is ./cyoa-step4 story3Test50  <  story3Test50/inputs/input0.txt
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
The story contains invalid number.
-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


4.6: Current test is ./cyoa-step4 story3Test51  <  story3Test51/inputs/input0.txt
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
The story contains invalid number.
-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


4.7: Current test is ./cyoa-step4 story3Test52  <  story3Test52/inputs/input0.txt
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
The story contains invalid long number. 
-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


4.8: Current test is ./cyoa-step4 story3Test53  <  story3Test53/inputs/input0.txt
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
The story contains invalid long number. 
-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


4.9: Current test is ./cyoa-step4 story3Test54  <  story3Test54/inputs/input0.txt
-----------------------------
You considered this a failure case:
The story contains invalid long number. 
But we did not.


4.10: Current test is ./cyoa-step4 story3  <  story3/inputs/input17.txt
-----------------------------
You considered this a failure case:
The story contains invalid long number. 
But we did not.


4.11: Current test is ./cyoa-step4 story3Test19  <  story3Test19/inputs/input17.txt
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
The story contains invalid input line.
-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


4.12: Current test is ./cyoa-step4 story3Test19  <  story3Test19/inputs/input16.txt
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
The story contains invalid input line.
-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


4.13: Current test is ./cyoa-step4 story3Test20  <  story3Test20/inputs/input17.txt
-----------------------------
You considered this a failure case:
The story contains invalid long number. 
But we did not.


4.14: Current test is ./cyoa-step4 story3Test20  <  story3Test20/inputs/input16.txt
-----------------------------
You considered this a failure case:
The story contains invalid long number. 
But we did not.


4.15: Current test is ./cyoa-step4 story3Test21  <  story3Test21/inputs/input17.txt
-----------------------------
You considered this a failure case:
The story contains invalid long number. 
But we did not.


4.16: Current test is ./cyoa-step4 story3Test21  <  story3Test21/inputs/input16.txt
-----------------------------
You considered this a failure case:
The story contains invalid long number. 
But we did not.


4.17: Current test is ./cyoa-step4 story3Test22  <  story3Test22/inputs/input17.txt
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
The story contains invalid long number. 
-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


4.18: Current test is ./cyoa-step4 story3Test22  <  story3Test22/inputs/input16.txt
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
The story contains invalid long number. 
-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


4.19: Current test is ./cyoa-step4 story3Test23  <  story3Test23/inputs/input17.txt
-----------------------------
You considered this a failure case:
The story contains invalid long number. 
But we did not.


4.20: Current test is ./cyoa-step4 story3Test23  <  story3Test23/inputs/input16.txt
-----------------------------
You considered this a failure case:
The story contains invalid long number. 
But we did not.


4.21: Current test is ./cyoa-step4 story3Test26  <  story3Test26/inputs/input17.txt
-----------------------------
You considered this a failure case:
The story contains invalid long number. 
But we did not.


4.22: Current test is ./cyoa-step4 story3Test26  <  story3Test26/inputs/input16.txt
-----------------------------
You considered this a failure case:
The story contains invalid long number. 
But we did not.


4.23: Current test is ./cyoa-step4 story3Test28  <  story3Test28/inputs/input17.txt
-----------------------------
You considered this a failure case:
The story contains invalid long number. 
But we did not.


4.24: Current test is ./cyoa-step4 story3Test28  <  story3Test28/inputs/input16.txt
-----------------------------
You considered this a failure case:
The story contains invalid long number. 
But we did not.


4.25: Current test is ./cyoa-step4 story3Test29  <  story3Test29/inputs/input17.txt
-----------------------------
You considered this a failure case:
The story contains invalid long number. 
But we did not.


4.26: Current test is ./cyoa-step4 story3Test29  <  story3Test29/inputs/input16.txt
-----------------------------
You considered this a failure case:
The story contains invalid long number. 
But we did not.


4.27: Current test is ./cyoa-step4 storyTest1  <  storyTest1/inputs/input0.txt
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
This story contains undefined page (not N, W nor L).
-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


4.28: Current test is ./cyoa-step4 storyTest2  <  storyTest2/inputs/input0.txt
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
The story contains page declaration line that its page file cannot be opened.
-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


4.29: Current test is ./cyoa-step4 storyTest3  <  storyTest3/inputs/input0.txt
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
The story contains invalid number.
-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


4.30: Current test is ./cyoa-step4 storyTest4  <  storyTest4/inputs/input0.txt
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
The story contains invalid number.
-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


4.31: Current test is ./cyoa-step4 storyTest5  <  storyTest5/inputs/input0.txt
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
The story contains page that the destination page of its choice does not exist.
-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


4.32: Current test is ./cyoa-step4 storyTest6  <  storyTest6/inputs/input0.txt
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
The input cannot finish the story.
-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


4.33: Current test is ./cyoa-step4 storyTest7  <  storyTest7/inputs/input0.txt
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
The choice cannot be matched with the current page.
-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


4.34: Current test is ./cyoa-step4 storyTest8  <  storyTest8/inputs/input0.txt
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
The story contains invalid number.
-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


4.35: Current test is ./cyoa-step4 storyTest9  <  storyTest9/inputs/input0.txt
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
The current page of the choice shows up before the page declaration.
-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


4.36: Current test is ./cyoa-step4 storyTest10  <  storyTest10/inputs/input0.txt
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
The win page of the story has choices, but it shouldn't.
-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


4.37: Current test is ./cyoa-step4 storyTest11  <  storyTest11/inputs/input0.txt
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
The lose page of the story has choices, but it shouldn't.
-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


4.38: Current test is ./cyoa-step4 storyTest12  <  storyTest12/inputs/input0.txt
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
There are pages that are not referenced in this story.
-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


4.39: Current test is ./cyoa-step4 storyTest13  <  storyTest13/inputs/input0.txt
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
There are pages that are not referenced in this story.
-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


4.40: Current test is ./cyoa-step4 storyTest14  <  storyTest14/inputs/input0.txt
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
No win or No lose page in this storty.
-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


4.41: Current test is ./cyoa-step4 storyTest15  <  storyTest15/inputs/input0.txt
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
The pages in this story are not consecutive.
-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


4.42: Current test is ./cyoa-step4 storyTest16  <  storyTest16/inputs/input0.txt
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
The story contains page that the destination page of its choice does not exist.
-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


4.43: Current test is ./cyoa-step4 storyTest  <  storyTest/inputs/input1.txt
-----------------------------
It looks like you got different output from us on that case.
Here is the diff (yours on left, ours on right):

Welcome to choose your own adventure.				Welcome to choose your own adventure.
Get ready for the thrilling tale of dragons and brunches.	Get ready for the thrilling tale of dragons and brunches.
Will you get help from Grew and/or Denevieve?			Will you get help from Grew and/or Denevieve?
Will you be eaten by a dragon?					Will you be eaten by a dragon?

Only you can decide....						Only you can decide....

What would you like to do?					What would you like to do?

 1. I am ready for this story!					 1. I am ready for this story!
One day, a strange old wizard comes to your village and tells	One day, a strange old wizard comes to your village and tells
there is an evil dragon lurking in the hills. This wizard's s	there is an evil dragon lurking in the hills. This wizard's s
why the village's goats and cows have been going missing late	why the village's goats and cows have been going missing late

The wizard tells you: "It is up to you, hero, to stop this dr	The wizard tells you: "It is up to you, hero, to stop this dr
else in this village is foolish...errrr I mean brave enough t	else in this village is foolish...errrr I mean brave enough t
dragon." 							dragon." 

The wizard offers you a choice of one of three magic items to	The wizard offers you a choice of one of three magic items to
your quest. 							your quest. 

The first is a magic whistle that lets you make any bird call	The first is a magic whistle that lets you make any bird call
want. The second is a pair of magic shoes that let you jump 1	want. The second is a pair of magic shoes that let you jump 1
air. The third is a magic toaster, which can take any item th	air. The third is a magic toaster, which can take any item th
into it, and turn it into perfectly cooked toast (optionally 	into it, and turn it into perfectly cooked toast (optionally 
and/or jam). 							and/or jam). 

"Choose wisely, for your quest and your village depend on you	"Choose wisely, for your quest and your village depend on you

What would you like to do?					What would you like to do?

 1. Choose the magic whistle.					 1. Choose the magic whistle.
 2. Choose the magic shoes.					 2. Choose the magic shoes.
 3. Choose the magic toaster.					 3. Choose the magic toaster.
That is not a valid choice, please try again			That is not a valid choice, please try again
							      |	That is not a valid choice, please try again
							      >	That is not a valid choice, please try again
							      >	That is not a valid choice, please try again
							      >	That is not a valid choice, please try again
							      >	That is not a valid choice, please try again
As you take the magic whistle from the wizard's hand, he disa	As you take the magic whistle from the wizard's hand, he disa
puff of smoke. You decide that you should give the whistle a 	puff of smoke. You decide that you should give the whistle a 
set off to deal with the dragon (after all, if you learned no	set off to deal with the dragon (after all, if you learned no
school, it was that testing is VERY important). 		school, it was that testing is VERY important). 

You think of a raven and blow on the whistle "CAW CAW CAW CAW	You think of a raven and blow on the whistle "CAW CAW CAW CAW
think of a chicken and blow "COCKADOODLEDOOOO". It seems like	think of a chicken and blow "COCKADOODLEDOOOO". It seems like
works great, though you wonder how many different birds you c	works great, though you wonder how many different birds you c
and how they would help you deal with the dragon. 		and how they would help you deal with the dragon. 

Putting that question in the back of your mind, you contempla	Putting that question in the back of your mind, you contempla
not you should get some help before you set out. On the one h	not you should get some help before you set out. On the one h
alone, you might be able to better sneak into the dragon's la	alone, you might be able to better sneak into the dragon's la
other hand, help might be useful.				other hand, help might be useful.

Fortunately for you, the two wisest people you know, Deneviev	Fortunately for you, the two wisest people you know, Deneviev
live in the next village over. Thinking about it for several 	live in the next village over. Thinking about it for several 
decide whom to go to for help.					decide whom to go to for help.

What would you like to do?					What would you like to do?

 1. Go to Denevieve for help.					 1. Go to Denevieve for help.
 2. Go to Grew for help.					 2. Go to Grew for help.
 3. Go alone.							 3. Go alone.
After thinking about it a bit, you decide that Denevieve is p	After thinking about it a bit, you decide that Denevieve is p
better choice. After all, her singing skills are likely to co	better choice. After all, her singing skills are likely to co
especially with your magic whistle. Maybe dragons can be tame	especially with your magic whistle. Maybe dragons can be tame
music and bird calls? That could be right, but you aren't sur	music and bird calls? That could be right, but you aren't sur
through that day of Magical Creature Biology class. 		through that day of Magical Creature Biology class. 

After knocking on the door, Denevieve is surprised to hear ab	After knocking on the door, Denevieve is surprised to hear ab
threat but is happy to help you. After all, you were her best	threat but is happy to help you. After all, you were her best
tested every piece of code extensively and incrementally. Sur	tested every piece of code extensively and incrementally. Sur
trusted with a quest about dragons.				trusted with a quest about dragons.

The two of you set off into the hills and find the cave of th	The two of you set off into the hills and find the cave of th
take a minute to confer about your musical options and come u	take a minute to confer about your musical options and come u
list of three possible combinations to tame the dragon. 	list of three possible combinations to tame the dragon. 

What would you like to do?					What would you like to do?

 1. Silent Night, accompanied by raven calls			 1. Silent Night, accompanied by raven calls
As you take the magic toaster from the wizard's hand, he disa	As you take the magic toaster from the wizard's hand, he disa
puff of smoke. You decide that you should give the toaster a 	puff of smoke. You decide that you should give the toaster a 
set off to deal with the dragon (after all, if you learned no	set off to deal with the dragon (after all, if you learned no
school, it was that testing is VERY important). 		school, it was that testing is VERY important). 

Having not had any breakfast, you are quite hungry, so testin	Having not had any breakfast, you are quite hungry, so testin
seems like a great solution to two problems. You grab a rock 	seems like a great solution to two problems. You grab a rock 
ground, stuff it in, and think of delicious toast with raspbe	ground, stuff it in, and think of delicious toast with raspbe
seconds later, out pops the most perfectly done toast with ju	seconds later, out pops the most perfectly done toast with ju
amount of butter and jam. Wow that is good! You spend a while	amount of butter and jam. Wow that is good! You spend a while
testing the toaster again and again "just to be sure". After 	testing the toaster again and again "just to be sure". After 
stuffed on toast, you start to wonder how this will help you 	stuffed on toast, you start to wonder how this will help you 
dragon. 							dragon. 

Putting that question in the back of your mind, you contempla	Putting that question in the back of your mind, you contempla
not you should get some help before you set out. On the one h	not you should get some help before you set out. On the one h
alone, you might be able to better sneak into the dragon's la	alone, you might be able to better sneak into the dragon's la
other hand, help might be useful.				other hand, help might be useful.

Fortunately for you, the two wisest people you know, Deneviev	Fortunately for you, the two wisest people you know, Deneviev
live in the next village over. Thinking about it for several 	live in the next village over. Thinking about it for several 
decide whom to go to for help.					decide whom to go to for help.

What would you like to do?					What would you like to do?

 1. Go alone.							 1. Go alone.
After thinking about it for a bit, you decide to go alone. Yo	After thinking about it for a bit, you decide to go alone. Yo
into the hills by yourself in search of the dragon. Unfortuna	into the hills by yourself in search of the dragon. Unfortuna
you are walking and trying to think up a plan, the dragon swo	you are walking and trying to think up a plan, the dragon swo
behind you and devours you. 					behind you and devours you. 

You have been eaten by a dragon.				You have been eaten by a dragon.

Sorry, you have lost. Better luck next time!			Sorry, you have lost. Better luck next time!
Your file did not match the expected output



4.44: Current test is ./cyoa-step4 storyTest  <  storyTest/inputs/input2.txt
-----------------------------
Your output looks good. Lets check valgrind
  - Valgrind was clean (no errors, no memory leaks)
Valgrind was clean


4.45: Current test is ./cyoa-step4 storyTest  <  storyTest/inputs/input3.txt
-----------------------------
Your output looks good. Lets check valgrind
  - Valgrind was clean (no errors, no memory leaks)
Valgrind was clean


4.46: Current test is ./cyoa-step4 storyTest  <  storyTest/inputs/input4.txt
-----------------------------
Your output looks good. Lets check valgrind
  - Valgrind was clean (no errors, no memory leaks)
Valgrind was clean


4.47: Current test is ./cyoa-step4 storyTest  <  storyTest/inputs/input5.txt
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
The input cannot finish the story.
-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


4.48: Current test is ./cyoa-step4 storyTest24  <  storyTest24/inputs/input0.txt
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
no char is a valid number.
-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean


4.49: Current test is ./cyoa-step4 storyTest25  <  storyTest25/inputs/input0.txt
-----------------------------
Great: we both considered this an error
----here is what you printed on stderr---
There are pages that are not referenced in this story.
-----------------------------------------
Lets check if it valgrinds:
Valgrind was clean
No request to check for intermediate deadline completion on step 4

You have NOT passed your test cases!
You should go and figure out/understand where thing went wrong
And fix the problem(s) before the deadline

Overall Grade: NO GRADE YET
